server:
  port: 8002
  address: 0.0.0.0
spring:
  application:
    name: gulimall-product
  data:
    redis:
      host: 127.0.0.1  # Redis服务器地址（实际项目填真实IP）
      port: 9003       # Redis端口（默认6379）
      password:        # 密码（如果Redis没设密码，留空）
      lettuce:
        pool:
          max-active: 16  # 最大连接数
          max-idle: 8     # 最大空闲连接
          min-idle: 4     # 最小空闲连接
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:9001/gulimall_pms?useSSL=false&serverTimezone=UTC&characterEncoding=utf8&allowPublicKeyRetrieval=true
    username: root
    password: 123456789
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        ip: 127.0.0.1
  jackson:
    default-property-inclusion: non_null

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
      logic-delete-value: 1
      logic-not-delete-value: 0

rocketmq:
  name-server: 127.0.0.1:9876
  producer:
    group: gulimall-product-producer   # ← 必须有，名字自取即可
elasticsearch:
  uris: http://localhost:9200
# Seata配置
seata:
  enabled: true
  tx-service-group: default  # 必须与服务端tx-service-group.default一致
  service:
    vgroup-mapping:
      default: default  # 必须与服务端store.vgroupMapping.default一致
  registry:
    type: nacos
    nacos:
      server-addr: 127.0.0.1:8848
      username: nacos
      password: nacos
      group: SEATA_GROUP
  config:
    type: nacos
    nacos:
      server-addr: 127.0.0.1:8848
      username: nacos
      password: nacos
      group: SEATA_GROUP
  data-source-proxy-mode: AT  # 2.0.0需明确指定代理模式