server:
  port: 8001  # 本服务启动端口
  address: 0.0.0.0
spring:
  application:
    name: gulimall-user

  datasource:
    url: jdbc:mysql://127.0.0.1:9001/gulimall_user?useSSL=false&serverTimezone=UTC&characterEncoding=utf8&allowPublicKeyRetrieval=true
    username: root
    password: 123456789
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        ip: 127.0.0.1
  data:
    redis:
      host: 127.0.0.1
      port: 9003
      timeout: 3000
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: 3000
mybatis:
  mapper-locations: classpath:/mapper/**/*.xml
  type-aliases-package: com.gulimall.user.entity

logging:
  level:
    com.gulimall: debug  # 开启调试日志（可选）

debug: true