server:
  port: 8003
  address: 0.0.0.0
rocketmq:
  name-server: 127.0.0.1:9876
  producer:
    group: gulimall-order-producer
spring:
  application:
    name: gulimall-order
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        ip: 127.0.0.1
  datasource:
    url: jdbc:mysql://127.0.0.1:9001/gulimall_pms?useSSL=false&serverTimezone=UTC&characterEncoding=utf8&allowPublicKeyRetrieval=true
    username: root
    password: 123456789
    driver-class-name: com.mysql.cj.jdbc.Driver

# Seata配置
seata:
  enabled: true
  enable-auto-data-source-proxy: true   # ★ 新增
  data-source-proxy-mode: AT
  tx-service-group: gulimall_tx_group
  service:
    vgroup-mapping:
      gulimall_tx_group: default
  registry:
    type: nacos
    nacos:
      server-addr: 127.0.0.1:8848
      username: nacos
      password: nacos
      group: SEATA_GROUP
      namespace: ""
      application: seata-server
      cluster: default
  config:
    type: nacos
    nacos:
      server-addr: 127.0.0.1:8848
      username: nacos
      password: nacos
      group: SEATA_GROUP
      namespace: ""