server:
  port: 8003
  address: 0.0.0.0
rocketmq:
  name-server: 127.0.0.1:9876
  producer:
    group: gulimall-order-producer
spring:
  application:
    name: gulimall-order
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        ip: 127.0.0.1
  datasource:
    url: jdbc:mysql://127.0.0.1:9001/gulimall_pms?useSSL=false&serverTimezone=UTC&characterEncoding=utf8&allowPublicKeyRetrieval=true
    username: root
    password: 123456789
    driver-class-name: com.mysql.cj.jdbc.Driver

# Seata配置
seata:
  enabled: true
  tx-service-group: gulimall_tx_group # 事务组名称（需与Seata Server配置一致）
  service:
    vgroup-mapping:
      gulimall_tx_group: default # 映射到Seata Server的集群名（与registry.conf一致）
  registry:
    type: nacos # 注册中心类型
    nacos:
      server-addr: localhost:8850 # Seata Server所在的Nacos地址
      application: seata-server # Seata Server的服务名（与registry.conf一致）
      group: SEATA_GROUP # 分组（与registry.conf一致）