server:
  port: 8003
  address: 0.0.0.0
rocketmq:
  name-server: 127.0.0.1:9876
  producer:
    group: gulimall-order-producer
spring:
  application:
    name: gulimall-order
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        ip: 127.0.0.1
  datasource:
    url: jdbc:mysql://127.0.0.1:9001/gulimall_pms?useSSL=false&serverTimezone=UTC&characterEncoding=utf8&allowPublicKeyRetrieval=true
    username: root
    password: 123456789
    driver-class-name: com.mysql.cj.jdbc.Driver