server:
  port: 88
  address: 0.0.0.0
spring:
  application:
    name: gulimall-gateway
  management:
    endpoints:
      web:
        exposure:
          include: "*"
    endpoint:
      gateway:
        enabled: true

  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        ip: 127.0.0.1
    gateway:
      discovery:
        locator:
          enabled: false  # 开启自动根据微服务名路由
      routes:
        - id: product_route
          uri: lb://gulimall-product
          predicates:
            - Path=/api/product/**
          filters:
            - StripPrefix=1

        - id: order_route
          uri: lb://gulimall-order
          predicates:
            - Path=/api/order/**
          filters:
            - StripPrefix=1

        - id: ware_route
          uri: lb://gulimall-ware
          predicates:
            - Path=/api/ware/**
          filters:
            - StripPrefix=1

        - id: user_route
          uri: lb://gulimall-user
          predicates:
            - Path=/api/user/**
          filters:
            - StripPrefix=1
