spring:
  application:
    name: gulimall-common
  data:
    redis:
      host: 127.0.0.1  # Redis服务器地址（实际项目填真实IP）
      port: 9003       # Redis端口（默认6379）
      password:        # 密码（如果Redis没设密码，留空）
      lettuce:
        pool:
          max-active: 16  # 最大连接数
          max-idle: 8     # 最大空闲连接
          min-idle: 4     # 最小空闲连接